export const ticketingTypes = {
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEMS: 'CLEAR_ITEMS',
  UPDATE_AMOUNT: 'UPDATE_AMOUNT',
  UPDATE_DATE: 'UPDATE_DATE',
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
  UPDATE_TITLE: 'UPDATE_TITLE',
}